### ISSUE TITLE
Week 9 Project Review

### ISSUE THREAD

**Issue by AlreadyAsleep** [dalebsellers/CL-capstone#1]
Below is a review of your project that will outline how it stacks up against the requirements and what opportunities I see.
Here is a link to the requirements for reference: https://docs.google.com/document/d/1OHe_R4irOpoKX3QGD3HZWCgNLaHScVuviWGa95Be830/edit#
## Mandatory Requirements
- Responsive Design: Lot's of responsiveness in the content and menu
- Javascript: Some javascript to do responsive menu and carousal
- Comments: Plenty and helpful ones
- 5 commits: 6 commits 
- README: check
## Feature Requirements
Based on our conversations and what I can see in your site I would attempt the following features from the requirements list:
- Hamburger menu there and looks good
- CSS Grid for main site content that changes from two to one columns on mobile
- Add a contact form that takes an email and validates it. 

Good work so far. Let's get everything tied together over the next few weeks

**Comment by dalebsellers** [comment]
Thank you Ben!
    On Saturday, July 4, 2020, 08:47:25 PM EDT, Ben <notifications@github.com> wrote:  
 
 


Below is a review of your project that will outline how it stacks up against the requirements and what opportunities I see.
Here is a link to the requirements for reference: https://docs.google.com/document/d/1OHe_R4irOpoKX3QGD3HZWCgNLaHScVuviWGa95Be830/edit#

Mandatory Requirements
   
   - Responsive Design: Lot's of responsiveness in the content and menu
   - Javascript: Some javascript to do responsive menu and carousal
   - Comments: Plenty and helpful ones
   - 5 commits: 6 commits
   - README: check

Feature Requirements

Based on our conversations and what I can see in your site I would attempt the following features from the requirements list:
   
   - Hamburger menu there and looks good
   - CSS Grid for main site content that changes from two to one columns on mobile
   - Add a contact form that takes an email and validates it.

Good work so far. Let's get everything tied together over the next few weeks

**Comment by dalebsellers** [comment]
I have resolved all of errors and implemented recommendations.
